// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tppwyjnknnlkmpbdyrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcHd5am5rbm5sa21wYmR5cm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDM4NTQsImV4cCI6MjA2NzQxOTg1NH0.b6aZFiyDuAIC4IbOYwXI1A3vXf1C6iFhvk_MJcHUU3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});